import express from 'express';
import cors from 'cors';
import { initializeApp, cert, applicationDefault, getApps } from 'firebase-admin/app';
import { getAuth } from 'firebase-admin/auth';
import { getFirestore, FieldValue } from 'firebase-admin/firestore';
import { Resend } from 'resend';
import crypto from 'node:crypto';
import {
    LANGUAGES, PRIMARY_MODEL, PRIMARY_THINKING, FALLBACK_MODEL, FALLBACK_THINKING,
    DICTIONARY_SCHEMA_VERSION, createTranslationService, buildGeminiCompatibilityRequests,
    geminiCompatibilityKey, isGeminiInvalidArgument
} from './translation-service.js';

const app = express();
const port = process.env.PORT || 3000;
const BACKEND_VERSION = '3.3.0';
const APP_ID = process.env.APP_ID || 'linguist-app-v7';
const ADMIN_UID = process.env.ADMIN_UID || 'rJvQjMmE6qMKmazel2NyvgGcVHw2';
const FEEDBACK_EMAIL_TO = process.env.FEEDBACK_EMAIL_TO || 'feedback@qelumi.com';
const FEEDBACK_EMAIL_FROM = process.env.FEEDBACK_EMAIL_FROM || '';
const allowedOrigins = (process.env.FRONTEND_ORIGINS || '').split(',').map(value => value.trim()).filter(Boolean);
const feedbackCategories = new Set(['suggestion', 'glitch', 'translation', 'other']);
const feedbackStatuses = new Set(['new', 'read', 'closed']);
const translationSources = new Set(['generated', 'dictionary_repair', 'global_dictionary', 'personal_history', 'image_analysis', 'language_validation']);
const translationOutcomes = new Set(['success', 'definitions_only', 'language_mismatch', 'not_found', 'error']);

function initialiseFirebaseAdmin() {
    if (getApps().length) return getApps()[0];
    if (process.env.FIREBASE_SERVICE_ACCOUNT_JSON) {
        const credential = JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_JSON);
        return initializeApp({ credential:cert(credential) });
    }
    return initializeApp({ credential:applicationDefault(), projectId:process.env.FIREBASE_PROJECT_ID || 'mylinguist28' });
}

initialiseFirebaseAdmin();
const auth = getAuth();
const db = getFirestore();
const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null;

const feedbackCollection = () => db.collection('artifacts').doc(APP_ID).collection('public').doc('data').collection('feedback');
const translationSearchCollection = () => db.collection('admin_metrics').doc('translation_searches').collection('items');
const timestampMillis = value => value?.toMillis?.() || Number(value) || 0;
const htmlEscape = value => String(value ?? '').replace(/[&<>"']/g, character => ({
    '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;'
}[character]));
const validEmail = value => typeof value === 'string' && value.length <= 320 && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
const categoryLabel = value => ({
    suggestion:'Feature suggestion', glitch:'Glitch / bug', translation:'Translation error', other:'Other'
}[value] || 'Other');
const sourceLabel = value => ({
    generated:'New — generated by API', dictionary_repair:'Existing dictionary entry repaired by API', global_dictionary:'Already in global dictionary',
    personal_history:'Already in user history', image_analysis:'New image analysis',
    language_validation:'Language validation'
}[value] || 'Unknown');

app.disable('x-powered-by');

// This route must receive the unparsed request body so Resend's signature can be verified.
app.post('/api/webhooks/resend', express.raw({ type:'application/json', limit:'1mb' }), async (req, res) => {
    try {
        if (!resend || !process.env.RESEND_WEBHOOK_SECRET) return res.status(503).json({ error:{ message:'Email webhook is not configured.' } });
        const event = resend.webhooks.verify({
            payload:req.body.toString('utf8'),
            headers:{
                id:req.get('svix-id'), timestamp:req.get('svix-timestamp'), signature:req.get('svix-signature')
            },
            webhookSecret:process.env.RESEND_WEBHOOK_SECRET
        });
        const emailId = event?.data?.email_id;
        if (!emailId) return res.json({ ok:true });
        const matches = await feedbackCollection().where('notificationEmailId', '==', emailId).limit(5).get();
        const status = event.type === 'email.delivered' ? 'delivered'
            : ['email.bounced', 'email.complained', 'email.failed', 'email.suppressed'].includes(event.type) ? 'failed'
                : event.type === 'email.delivery_delayed' ? 'delayed'
                    : event.type === 'email.sent' ? 'sent' : null;
        if (status) {
            await Promise.all(matches.docs.map(document => document.ref.update({
                notificationStatus:status,
                notificationEvent:event.type,
                notificationUpdatedAt:FieldValue.serverTimestamp(),
                ...(status === 'delivered' ? { notificationDeliveredAt:FieldValue.serverTimestamp() } : {})
            })));
        }
        res.json({ ok:true });
    } catch (error) {
        res.status(400).json({ error:{ message:'Invalid webhook request.' } });
    }
});

app.use(cors({ origin(origin, callback) {
    if (!origin || allowedOrigins.length === 0 || allowedOrigins.includes(origin)) return callback(null, true);
    return callback(new Error('Origin not allowed'));
} }));
app.use(express.json({ limit:'10mb' }));

const requestBuckets = new Map();
setInterval(() => {
    const now = Date.now();
    for (const [key, bucket] of requestBuckets) if (bucket.resetAt <= now) requestBuckets.delete(key);
}, 15 * 60_000).unref();

function rateLimit({ windowMs, max, key = req => req.ip }) {
    return (req, res, next) => {
        const now = Date.now(); const bucketKey = key(req); const current = requestBuckets.get(bucketKey);
        if (!current || current.resetAt <= now) requestBuckets.set(bucketKey, { count:1, resetAt:now + windowMs });
        else if (++current.count > max) return res.status(429).json({ error:{ message:'Too many requests. Please try again later.' } });
        next();
    };
}

async function requireUser(req, res, next) {
    try {
        const token = String(req.headers.authorization || '').replace(/^Bearer\s+/i, '');
        if (!token) return res.status(401).json({ error:{ message:'Authentication required.' } });
        req.user = await auth.verifyIdToken(token, true);
        next();
    } catch (_) {
        return res.status(401).json({ error:{ message:'Invalid or expired session.' } });
    }
}

function requireAdmin(req, res, next) {
    if (req.user?.uid !== ADMIN_UID && req.user?.admin !== true) return res.status(403).json({ error:{ message:'Administrator access required.' } });
    next();
}

async function recordUsage(uid, operation, metadata = {}) {
    const day = new Date().toISOString().slice(0, 10); const ref = db.doc(`admin_metrics/api_usage/days/${day}`);
    const latencyMs = Math.max(0, Number(metadata.latencyMs || 0));
    const inputTokens = Math.max(0, Number(metadata.inputTokens || 0));
    const visibleOutputTokens = Math.max(0, Number(metadata.visibleOutputTokens || 0));
    const reasoningTokens = Math.max(0, Number(metadata.reasoningTokens || 0));
    const totalTokens = Math.max(0, Number(metadata.totalTokens || inputTokens + visibleOutputTokens + reasoningTokens));
    const modelKey = String(metadata.model || 'none').replace(/[^A-Za-z0-9_-]/g, '_').slice(0, 80);
    await ref.set({
        day, updatedAt:FieldValue.serverTimestamp(), total:FieldValue.increment(1),
        operations:{ [operation]:FieldValue.increment(1) },
        models:{ [modelKey]:FieldValue.increment(1) },
        inputTokens:FieldValue.increment(inputTokens),
        outputTokens:FieldValue.increment(visibleOutputTokens),
        reasoningTokens:FieldValue.increment(reasoningTokens),
        totalTokens:FieldValue.increment(totalTokens),
        totalLatencyMs:FieldValue.increment(latencyMs),
        fallbackCalls:FieldValue.increment(operation.includes('fallback') ? 1 : 0),
        cacheHits:FieldValue.increment(operation === 'translation_cache_hit' ? 1 : 0)
    }, { merge:true });
    await db.collection('admin_metrics').doc('events').collection('items').add({
        uid, operation, metadata, timestamp:FieldValue.serverTimestamp()
    });
}

function measuredGeminiUsage(data, startedAt, model, thinkingLevel) {
    const usage = data?.usageMetadata || {};
    return {
        model,
        thinkingLevel,
        latencyMs:Math.max(0, Math.round(performance.now() - startedAt)),
        inputTokens:Number(usage.promptTokenCount || 0),
        visibleOutputTokens:Number(usage.candidatesTokenCount || 0),
        reasoningTokens:Number(usage.thoughtsTokenCount || 0),
        totalTokens:Number(usage.totalTokenCount || 0)
    };
}

const translationService = createTranslationService({ db, FieldValue, recordUsage });
const genericCompatibilityModes = new Map();

async function callGemini(body, { model = PRIMARY_MODEL, thinkingLevel = PRIMARY_THINKING, timeoutMs = 25_000 } = {}) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) throw new Error('Server misconfiguration: GEMINI_API_KEY is missing.');
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), timeoutMs);
    try {
        const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`;
        const send = requestBody => fetch(endpoint, {
            method:'POST', signal:controller.signal,
            headers:{ 'Content-Type':'application/json', 'x-goog-api-key':apiKey }, body:JSON.stringify(requestBody)
        });
        const compatibilityKey = geminiCompatibilityKey(model, body);
        const preferredMode = genericCompatibilityModes.get(compatibilityKey);
        const variants = buildGeminiCompatibilityRequests(body, thinkingLevel);
        if (preferredMode) variants.sort((left, right) => Number(right.mode === preferredMode) - Number(left.mode === preferredMode));
        let response; let data; let selectedMode = variants[0]?.mode || 'structured';
        const rejectedModes = [];
        for (const variant of variants) {
            selectedMode = variant.mode;
            response = await send(variant.body);
            data = await response.json().catch(() => ({}));
            if (response.ok) {
                genericCompatibilityModes.set(compatibilityKey, selectedMode);
                break;
            }
            if (!isGeminiInvalidArgument(response, data)) break;
            rejectedModes.push(selectedMode);
        }
        if (!response.ok && isGeminiInvalidArgument(response, data)) {
            console.warn('Generic Gemini route rejected every compatible request form.', {
                model, rejectedModes, providerStatus:data?.error?.status || 'INVALID_ARGUMENT',
                providerMessage:String(data?.error?.message || '').slice(0, 300)
            });
            const error = new Error('The translation model rejected its request configuration. Verify that Render uses the Tier 1 Gemini API key and the model variables shown in DEPLOYMENT.md.');
            error.status = 502; error.code = 'MODEL_REQUEST_INVALID'; throw error;
        }
        if (!response.ok) { const error = new Error(data?.error?.message || 'Gemini request failed.'); error.status = response.status; throw error; }
        return data;
    } catch (error) {
        if (error.name === 'AbortError') {
            const timeoutError = new Error(`${model} timed out.`); timeoutError.status = 504; throw timeoutError;
        }
        throw error;
    } finally { clearTimeout(timeout); }
}

function translationContext(body) {
    const query = String(body?.query || '').normalize('NFKC').trim().replace(/\s+/gu, ' ').slice(0, 300);
    const fromLang = String(body?.fromLang || '').trim().toUpperCase();
    const toLang = String(body?.toLang || '').trim().toUpperCase();
    if (!query) throw Object.assign(new Error('A word or expression is required.'), { status:400 });
    if (!LANGUAGES[fromLang] || !LANGUAGES[toLang]) throw Object.assign(new Error('Unsupported source or destination language.'), { status:400 });
    return { query, fromLang, toLang, definitionsOnly:body?.definitionsOnly === true || fromLang === toLang };
}

async function sendFeedbackNotification(feedbackId, feedback) {
    if (!resend || !FEEDBACK_EMAIL_FROM || !FEEDBACK_EMAIL_TO) {
        const error = new Error('Feedback email delivery is not configured.');
        error.code = 'email/not-configured';
        throw error;
    }
    const submitted = new Date(feedback.date).toISOString();
    const replyTo = validEmail(feedback.replyEmail) ? feedback.replyEmail : (validEmail(feedback.accountEmail) ? feedback.accountEmail : undefined);
    const plainText = [
        `Category: ${categoryLabel(feedback.category)}`,
        `Date: ${submitted}`,
        `User UID: ${feedback.uid}`,
        `Account email: ${feedback.accountEmail || 'Not available'}`,
        `Reply address: ${replyTo || 'Not supplied'}`,
        feedback.attachmentName ? `Attachment: ${feedback.attachmentName} (available in the Administrator Dashboard)` : '',
        '', 'Feedback:', feedback.text
    ].filter(line => line !== '').join('\n');
    const html = `<h2>New Qelumi feedback</h2>
        <table cellpadding="6" cellspacing="0" style="border-collapse:collapse">
            <tr><td><b>Category</b></td><td>${htmlEscape(categoryLabel(feedback.category))}</td></tr>
            <tr><td><b>Date</b></td><td>${htmlEscape(submitted)}</td></tr>
            <tr><td><b>User UID</b></td><td><code>${htmlEscape(feedback.uid)}</code></td></tr>
            <tr><td><b>Account email</b></td><td>${htmlEscape(feedback.accountEmail || 'Not available')}</td></tr>
            <tr><td><b>Reply address</b></td><td>${htmlEscape(replyTo || 'Not supplied')}</td></tr>
            ${feedback.attachmentName ? `<tr><td><b>Attachment</b></td><td>${htmlEscape(feedback.attachmentName)} (available in the Administrator Dashboard)</td></tr>` : ''}
        </table>
        <h3>Feedback</h3><div style="white-space:pre-wrap">${htmlEscape(feedback.text)}</div>`;
    const { data, error } = await resend.emails.send({
        from:FEEDBACK_EMAIL_FROM,
        to:[FEEDBACK_EMAIL_TO],
        subject:`[Qelumi Feedback] ${categoryLabel(feedback.category)}`,
        text:plainText,
        html,
        ...(replyTo ? { replyTo } : {}),
        tags:[
            { name:'category', value:feedback.category },
            { name:'feedback_id', value:feedbackId.replace(/[^A-Za-z0-9_-]/g, '_') }
        ]
    }, { idempotencyKey:`qelumi-feedback/${feedbackId}` });
    if (error) throw new Error(error.message || 'Email provider rejected the notification.');
    return data;
}

async function resolveUserEmails(uids) {
    const identifiers = [...new Set(uids.filter(Boolean))];
    const emails = new Map();
    for (let index = 0; index < identifiers.length; index += 100) {
        const batch = identifiers.slice(index, index + 100);
        try {
            const result = await auth.getUsers(batch.map(uid => ({ uid })));
            result.users.forEach(userRecord => emails.set(userRecord.uid, userRecord.email || ''));
        } catch (error) {
            console.warn('Unable to resolve some user emails.', error.message);
        }
    }
    return emails;
}

app.get('/health', (_req, res) => res.json({
    ok:true, service:'linguist-backend', version:BACKEND_VERSION, schemaVersion:DICTIONARY_SCHEMA_VERSION,
    requestCompatibility:'adaptive-json-v2',
    models:{ primary:PRIMARY_MODEL, primaryThinking:PRIMARY_THINKING, fallback:FALLBACK_MODEL, fallbackThinking:FALLBACK_THINKING },
    feedbackEmailConfigured:!!(resend && FEEDBACK_EMAIL_FROM && FEEDBACK_EMAIL_TO)
}));

app.post('/api/auth/email-exists', rateLimit({ windowMs:15 * 60_000, max:20, key:req => `email:${req.ip}` }), async (req, res) => {
    try {
        await auth.getUserByEmail(String(req.body?.email || '').trim().toLowerCase());
        res.json({ exists:true });
    } catch (error) {
        if (error.code === 'auth/user-not-found') return res.json({ exists:false });
        res.status(500).json({ error:{ message:'Unable to check that account.' } });
    }
});

app.post('/api/gemini', requireUser, rateLimit({ windowMs:60 * 60_000, max:80, key:req => `gemini:${req.user.uid}` }), async (req, res) => {
    try {
        let data;
        let started = performance.now();
        try {
            data = await callGemini(req.body);
            recordUsage(req.user.uid, 'gemini_primary', measuredGeminiUsage(data, started, PRIMARY_MODEL, PRIMARY_THINKING)).catch(() => {});
        } catch (primaryError) {
            recordUsage(req.user.uid, 'gemini_primary_error', {
                model:PRIMARY_MODEL, thinkingLevel:PRIMARY_THINKING,
                latencyMs:Math.max(0, Math.round(performance.now() - started)), errorCode:primaryError.code || 'REQUEST_FAILED'
            }).catch(() => {});
            started = performance.now();
            data = await callGemini(req.body, { model:FALLBACK_MODEL, thinkingLevel:FALLBACK_THINKING });
            recordUsage(req.user.uid, 'gemini_fallback', measuredGeminiUsage(data, started, FALLBACK_MODEL, FALLBACK_THINKING)).catch(() => {});
        }
        res.json(data);
    } catch (error) {
        res.status(error.status || 500).json({ error:{ message:error.message } });
    }
});

app.post('/api/translate', requireUser, rateLimit({ windowMs:60 * 60_000, max:120, key:req => `translate:${req.user.uid}` }), async (req, res) => {
    try {
        const context = translationContext(req.body);
        const forceRefresh = req.body?.forceRefresh === true && (req.user.uid === ADMIN_UID || req.user.admin === true);
        const response = await translationService.getCore(context, req.user.uid, { forceRefresh });
        res.json(response);
    } catch (error) {
        res.status(error.status || 500).json({ error:{ message:error.message, code:error.code || 'TRANSLATION_FAILED' } });
    }
});

app.post('/api/translate/contexts', requireUser, rateLimit({ windowMs:60 * 60_000, max:120, key:req => `contexts:${req.user.uid}` }), async (req, res) => {
    try {
        const context = translationContext(req.body);
        res.json(await translationService.getContexts(context, req.user.uid));
    } catch (error) {
        res.status(error.status || 500).json({ error:{ message:error.message, code:error.code || 'CONTEXTS_FAILED' } });
    }
});

app.post('/api/game/distractors', requireUser, rateLimit({ windowMs:60 * 60_000, max:30, key:req => `distractors:${req.user.uid}` }), async (req, res) => {
    try {
        const fromLang = String(req.body?.fromLang || '').trim().toUpperCase();
        const toLang = String(req.body?.toLang || '').trim().toUpperCase();
        const original = String(req.body?.original || '').trim().slice(0, 500);
        const translated = String(req.body?.translated || '').trim().slice(0, 500);
        const correct = String(req.body?.correct || '').trim().slice(0, 200);
        const count = Math.min(4, Math.max(2, Number(req.body?.count || 4)));
        if (!LANGUAGES[fromLang] || !LANGUAGES[toLang] || !original || !correct) {
            return res.status(400).json({ error:{ message:'A valid quiz sentence, answer and language pair are required.' } });
        }
        res.json(await translationService.getDistractors({ fromLang, toLang, original, translated, correct, count }, req.user.uid));
    } catch (error) {
        res.status(error.status || 500).json({ error:{ message:error.message, code:error.code || 'DISTRACTORS_FAILED' } });
    }
});

app.post('/api/feedback', requireUser, rateLimit({ windowMs:60 * 60_000, max:10, key:req => `feedback:${req.user.uid}` }), async (req, res) => {
    const category = feedbackCategories.has(req.body?.category) ? req.body.category : (feedbackCategories.has(req.body?.type) ? req.body.type : 'other');
    const text = String(req.body?.text || '').trim();
    const replyEmail = String(req.body?.replyEmail || req.body?.email || '').trim().toLowerCase();
    const attachmentName = String(req.body?.attachmentName || '').trim().slice(0, 240);
    const attachmentData = typeof req.body?.attachmentData === 'string' ? req.body.attachmentData : '';
    if (!text || text.length > 10_000) return res.status(400).json({ error:{ message:'Feedback must contain between 1 and 10,000 characters.' } });
    if (replyEmail && !validEmail(replyEmail)) return res.status(400).json({ error:{ message:'The reply email address is invalid.' } });
    if (attachmentData.length > 700_000) return res.status(413).json({ error:{ message:'The feedback attachment is too large.' } });

    const feedbackRef = feedbackCollection().doc();
    const feedback = {
        uid:req.user.uid,
        accountEmail:req.user.email || '',
        replyEmail,
        category,
        type:category,
        text,
        date:Date.now(),
        status:'new',
        notificationStatus:'pending',
        notificationAttempts:0,
        hasAttachment:!!attachmentData,
        createdAt:FieldValue.serverTimestamp(),
        ...(attachmentName ? { attachmentName } : {}),
        ...(attachmentData ? { attachmentData } : {})
    };
    await feedbackRef.set(feedback);
    try {
        const delivery = await sendFeedbackNotification(feedbackRef.id, feedback);
        await feedbackRef.update({
            notificationStatus:'sent', notificationEmailId:delivery?.id || '',
            notificationAttempts:FieldValue.increment(1), notificationSentAt:FieldValue.serverTimestamp(),
            notificationError:FieldValue.delete()
        });
        res.status(201).json({ ok:true, id:feedbackRef.id, notificationStatus:'sent' });
    } catch (error) {
        const status = error.code === 'email/not-configured' ? 'not_configured' : 'failed';
        await feedbackRef.update({
            notificationStatus:status, notificationAttempts:FieldValue.increment(1),
            notificationError:String(error.message || 'Notification failed.').slice(0, 500),
            notificationUpdatedAt:FieldValue.serverTimestamp()
        });
        res.status(201).json({ ok:true, id:feedbackRef.id, notificationStatus:status });
    }
});

app.post('/api/translation-events', requireUser, rateLimit({ windowMs:60 * 60_000, max:300, key:req => `translation-events:${req.user.uid}` }), async (req, res) => {
    const query = String(req.body?.query || '').normalize('NFKC').trim().replace(/\s+/g, ' ').slice(0, 300);
    const fromLang = String(req.body?.fromLang || '').toUpperCase().slice(0, 5);
    const toLang = String(req.body?.toLang || '').toUpperCase().slice(0, 5);
    const source = translationSources.has(req.body?.source) ? req.body.source : 'generated';
    const outcome = translationOutcomes.has(req.body?.outcome) ? req.body.outcome : 'success';
    if (!query) return res.status(400).json({ error:{ message:'A searched word or expression is required.' } });
    const cacheStatus = source === 'global_dictionary' || source === 'dictionary_repair' ? 'common_dictionary'
        : source === 'generated' || source === 'image_analysis' ? 'new'
            : source === 'personal_history' ? 'personal_history' : 'not_applicable';
    const eventRef = translationSearchCollection().doc();
    await eventRef.set({
        uid:req.user.uid,
        userEmail:req.user.email || '',
        query,
        queryLower:query.toLocaleLowerCase(),
        fromLang,
        toLang,
        source,
        sourceLabel:sourceLabel(source),
        cacheStatus,
        outcome,
        definitionsOnly:req.body?.definitionsOnly === true,
        timestamp:Date.now(),
        createdAt:FieldValue.serverTimestamp(),
        error:outcome === 'error' ? String(req.body?.error || '').slice(0, 500) : ''
    });
    res.status(201).json({ ok:true, id:eventRef.id });
});

app.post('/api/jobs', requireUser, rateLimit({ windowMs:60 * 60_000, max:20, key:req => `jobs:${req.user.uid}` }), async (req, res) => {
    const jobRef = db.collection('translation_jobs').doc();
    await jobRef.set({
        uid:req.user.uid, status:'queued', createdAt:FieldValue.serverTimestamp(),
        requestHash:crypto.createHash('sha256').update(JSON.stringify(req.body)).digest('hex')
    });
    res.status(202).json({ jobId:jobRef.id, status:'queued' });
    try {
        await jobRef.update({ status:'running', startedAt:FieldValue.serverTimestamp() });
        let result; let operation = 'background_job_primary'; let model = PRIMARY_MODEL; let thinkingLevel = PRIMARY_THINKING;
        let started = performance.now();
        try { result = await callGemini(req.body); }
        catch (_) {
            operation = 'background_job_fallback'; model = FALLBACK_MODEL; thinkingLevel = FALLBACK_THINKING;
            started = performance.now();
            result = await callGemini(req.body, { model, thinkingLevel });
        }
        await jobRef.update({ status:'completed', result, completedAt:FieldValue.serverTimestamp() });
        recordUsage(req.user.uid, operation, measuredGeminiUsage(result, started, model, thinkingLevel)).catch(() => {});
    } catch (error) {
        await jobRef.update({ status:'failed', error:error.message, completedAt:FieldValue.serverTimestamp() });
    }
});

app.get('/api/jobs/:id', requireUser, async (req, res) => {
    const snapshot = await db.collection('translation_jobs').doc(req.params.id).get();
    if (!snapshot.exists || (snapshot.data().uid !== req.user.uid && req.user.uid !== ADMIN_UID)) return res.status(404).json({ error:{ message:'Job not found.' } });
    res.json({ id:snapshot.id, ...snapshot.data() });
});

app.post('/api/admin/bootstrap', requireUser, requireAdmin, async (req, res) => {
    await auth.setCustomUserClaims(req.user.uid, { admin:true });
    res.json({ ok:true, message:'Administrator claim assigned. Sign out and back in to refresh it.' });
});

app.get('/api/admin/metrics', requireUser, requireAdmin, async (_req, res) => {
    const [days, jobs, events] = await Promise.all([
        db.collection('admin_metrics').doc('api_usage').collection('days').orderBy('day', 'desc').limit(30).get(),
        db.collection('translation_jobs').orderBy('createdAt', 'desc').limit(50).get(),
        db.collection('admin_metrics').doc('events').collection('items').orderBy('timestamp', 'desc').limit(100).get()
    ]);
    res.json({
        usage:days.docs.map(document => ({ id:document.id, ...document.data() })),
        jobs:jobs.docs.map(document => ({ id:document.id, ...document.data(), result:undefined })),
        events:events.docs.map(document => ({ id:document.id, ...document.data(), timestamp:timestampMillis(document.data().timestamp) }))
    });
});

app.get('/api/admin/dictionary', requireUser, requireAdmin, async (req, res) => {
    const limit = Math.min(Number(req.query.limit) || 100, 500);
    const snapshot = await db.collectionGroup('global_dictionary').limit(limit).get();
    res.json({ entries:snapshot.docs.map(document => ({ id:document.id, path:document.ref.path, ...document.data(), fullJSON:undefined })) });
});

app.delete('/api/admin/dictionary/:id', requireUser, requireAdmin, async (req, res) => {
    await db.doc(`artifacts/${APP_ID}/public/data/global_dictionary/${req.params.id}`).delete();
    res.json({ ok:true });
});

app.get('/api/admin/feedback', requireUser, requireAdmin, async (req, res) => {
    const limit = Math.min(Number(req.query.limit) || 500, 2_000);
    const snapshot = await feedbackCollection()
        .select('uid', 'accountEmail', 'replyEmail', 'email', 'category', 'type', 'text', 'date', 'status',
            'notificationStatus', 'notificationAttempts', 'notificationEmailId', 'notificationError',
            'attachmentName', 'hasAttachment', 'createdAt')
        .orderBy('date', 'desc').limit(limit).get();
    res.json({ feedback:snapshot.docs.map(document => {
        const data = document.data();
        return {
            id:document.id, ...data, date:timestampMillis(data.date), createdAt:timestampMillis(data.createdAt),
            hasAttachment:data.hasAttachment === true || !!data.attachmentName
        };
    }) });
});

app.get('/api/admin/feedback/:id/attachment', requireUser, requireAdmin, async (req, res) => {
    const snapshot = await feedbackCollection().doc(req.params.id).get();
    if (!snapshot.exists || !snapshot.data().attachmentData) return res.status(404).json({ error:{ message:'Attachment not found.' } });
    res.json({ attachmentName:snapshot.data().attachmentName || 'attachment', attachmentData:snapshot.data().attachmentData });
});

app.patch('/api/admin/feedback/:id', requireUser, requireAdmin, async (req, res) => {
    if (!feedbackStatuses.has(req.body?.status)) return res.status(400).json({ error:{ message:'Invalid feedback status.' } });
    await feedbackCollection().doc(req.params.id).update({
        status:req.body.status, reviewedAt:FieldValue.serverTimestamp(), reviewedBy:req.user.uid
    });
    res.json({ ok:true, status:req.body.status });
});

app.post('/api/admin/feedback/:id/retry', requireUser, requireAdmin, async (req, res) => {
    const feedbackRef = feedbackCollection().doc(req.params.id);
    const snapshot = await feedbackRef.get();
    if (!snapshot.exists) return res.status(404).json({ error:{ message:'Feedback not found.' } });
    try {
        const delivery = await sendFeedbackNotification(snapshot.id, snapshot.data());
        await feedbackRef.update({
            notificationStatus:'sent', notificationEmailId:delivery?.id || '',
            notificationAttempts:FieldValue.increment(1), notificationSentAt:FieldValue.serverTimestamp(),
            notificationError:FieldValue.delete()
        });
        res.json({ ok:true, notificationStatus:'sent', notificationEmailId:delivery?.id || '' });
    } catch (error) {
        const status = error.code === 'email/not-configured' ? 'not_configured' : 'failed';
        await feedbackRef.update({
            notificationStatus:status, notificationAttempts:FieldValue.increment(1),
            notificationError:String(error.message || 'Notification failed.').slice(0, 500),
            notificationUpdatedAt:FieldValue.serverTimestamp()
        });
        res.status(502).json({ error:{ message:error.message }, notificationStatus:status });
    }
});

app.get('/api/admin/searches', requireUser, requireAdmin, async (req, res) => {
    const limit = Math.min(Number(req.query.limit) || 2_000, 5_000);
    const historyBaseQuery = db.collectionGroup('history').select('query', 'fromLang', 'toLang', 'timestamp');
    const historyQuery = historyBaseQuery.orderBy('timestamp', 'desc').limit(limit).get()
        .catch(error => {
            console.warn('History collection-group index is still building; using unordered fallback.', error.message);
            return historyBaseQuery.limit(limit).get();
        });
    const [auditSnapshot, historySnapshot] = await Promise.all([
        translationSearchCollection().orderBy('timestamp', 'desc').limit(limit).get(),
        historyQuery
    ]);
    const auditEvents = auditSnapshot.docs.map(document => ({
        id:document.id, ...document.data(), timestamp:timestampMillis(document.data().timestamp), legacy:false
    }));
    const appHistory = historySnapshot.docs.filter(document => document.ref.path.startsWith(`artifacts/${APP_ID}/users/`));
    const historyUids = appHistory.map(document => document.ref.path.split('/')[3]);
    const emailMap = await resolveUserEmails(historyUids);
    const auditByKey = new Map();
    for (const event of auditEvents) {
        const key = `${event.uid}|${String(event.query || '').toLocaleLowerCase()}|${event.fromLang || ''}|${event.toLang || ''}`;
        if (!auditByKey.has(key)) auditByKey.set(key, []);
        auditByKey.get(key).push(event.timestamp);
    }
    const legacyEvents = appHistory.flatMap(document => {
        const data = document.data();
        const uid = document.ref.path.split('/')[3];
        const timestamp = timestampMillis(data.timestamp);
        const key = `${uid}|${String(data.query || '').toLocaleLowerCase()}|${data.fromLang || ''}|${data.toLang || ''}`;
        const duplicate = (auditByKey.get(key) || []).some(auditTime => Math.abs(auditTime - timestamp) < 15_000);
        if (duplicate) return [];
        return [{
            id:`legacy:${document.ref.path}`,
            uid,
            userEmail:emailMap.get(uid) || '',
            query:data.query || '',
            queryLower:String(data.query || '').toLocaleLowerCase(),
            fromLang:data.fromLang || '',
            toLang:data.toLang || '',
            source:'legacy_history',
            sourceLabel:'Legacy history — original source unknown',
            cacheStatus:'unknown',
            outcome:'success',
            timestamp,
            legacy:true
        }];
    });
    const searches = [...auditEvents, ...legacyEvents].sort((first, second) => second.timestamp - first.timestamp);
    res.json({ searches, auditCount:auditEvents.length, legacyCount:legacyEvents.length });
});

app.use((error, _req, res, _next) => res.status(error.message === 'Origin not allowed' ? 403 : 500).json({ error:{ message:error.message } }));
app.listen(port, () => console.log(`Qelumi secure backend running on port ${port}`));
